# SPRING - APPLICATION
spring.application.name=backend_document

# SPRING - DATASOURCE
spring.datasource.url=${SUPABASE_URL}
spring.datasource.username=${SUPABASE_USERNAME}
spring.datasource.password=${SUPABASE_PASSWORD}

spring.datasource.hikari.initializationFailTimeout=60000
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.connection-init-sql=SET hnsw.ef_search = 100

# SPRING - JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

#SPRING - SERVLET
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=500MB

# SERVER
server.address=0.0.0.0
server.port=${PORT:9090}

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# GEMINI
gemini.api-key=${GEMINI_API_KEY}
gemini.embedding-url=${GEMINI_EMBEDDING_URL}
gemini.batch-embedding-url=${GEMINI_BATCH_EMBEDDING_URL}