spring.application.name=backend_gateway

server.address=0.0.0.0
server.port=7070

# Spring Cloud Gateway

spring.cloud.gateway.server.webflux.routes[0].id=route_to_server_2
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:9090
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/documents/**
spring.cloud.gateway.server.webflux.routes[0].order=1

spring.cloud.gateway.server.webflux.routes[1].id=route_to_server_1
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8080
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/**
spring.cloud.gateway.server.webflux.routes[1].order=2

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:5173
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-methods=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allow-credentials=true